# Generated by Django 4.2.20 on 2025-03-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
